# Generated by Django 2.2.6 on 2019-11-09 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('page_name', models.CharField(max_length=100, verbose_name='HTML page')),
            ],
        ),
        migrations.CreateModel(
            name='FrontText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000, verbose_name='HTML text')),
                ('front_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.FrontPage')),
            ],
        ),
    ]
