# Generated by Django 2.2.6 on 2019-11-11 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='HTML image')),
                ('front_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='front.FrontPage')),
            ],
        ),
    ]
