# Generated by Django 2.2.6 on 2019-11-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frontpage',
            name='page_text',
        ),
        migrations.AddField(
            model_name='fronttext',
            name='front_page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='front.FrontPage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='fronttext',
            name='text',
            field=models.TextField(max_length=1000, verbose_name='HTML text'),
        ),
    ]
