# Generated by Django 2.2.6 on 2019-11-11 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('front', '0002_frontimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontimage',
            name='image_name',
            field=models.CharField(default=1, max_length=20, verbose_name='HTML image name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fronttext',
            name='text_name',
            field=models.CharField(default=1, max_length=20, verbose_name='HTML text name'),
            preserve_default=False,
        ),
    ]
