# Generated by Django 2.2.6 on 2019-10-29 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item_name',
            new_name='pizza_obj',
        ),
    ]
