# Generated by Django 2.2.6 on 2019-10-27 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20191025_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='item',
            new_name='item_id',
        ),
    ]
