# Generated by Django 2.2.6 on 2019-10-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Taste',
        ),
        migrations.AlterModelOptions(
            name='taste',
            options={'verbose_name': 'Taste', 'verbose_name_plural': 'Tastes'},
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='category',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='content',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='description',
        ),
        migrations.RemoveField(
            model_name='size',
            name='active',
        ),
        migrations.RemoveField(
            model_name='size',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='size',
            name='price',
        ),
        migrations.RemoveField(
            model_name='size',
            name='type',
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.SmallIntegerField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='size',
            field=models.ManyToManyField(to='catalog.Size', verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='taste',
            field=models.ManyToManyField(to='catalog.Taste', verbose_name='Taste'),
        ),
        migrations.AddField(
            model_name='pizza',
            name='text_long',
            field=models.TextField(default=1, verbose_name='Long text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pizza',
            name='text_short',
            field=models.CharField(default=1, max_length=100, verbose_name='Short text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='size',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.DeleteModel(
            name='PromoCodeGroup',
        ),
    ]
