# Generated by Django 2.2.6 on 2019-10-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='taste',
            new_name='filter',
        ),
    ]
