# Generated by Django 2.2.6 on 2019-10-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20191021_0128'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='active',
            field=models.BooleanField(default=1, verbose_name='Active'),
            preserve_default=False,
        ),
    ]
