# Generated by Django 2.2.6 on 2019-10-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_pizza_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='item_id',
            field=models.SmallIntegerField(default=1, unique=True, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
