# Generated by Django 2.2.6 on 2019-10-24 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_pizza_item_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pizza',
            old_name='item_id',
            new_name='pizza_id',
        ),
    ]
